### ISSUE TITLE
Cyclic dependency between modules causes install to fail

### ISSUE THREAD

**Issue by clarenceb** [maestrodev/librarian-puppet#14]
Hi, thanks for forking librarian-puppet to fix the "-rc-x.y.z" issue.  I am experiencing a different issue now but one that might be due to the module implementer creating a cyclic dependency rather than librarian-puppet issue.

My Puppetfile:
`mod 'theforeman/foreman', "1.2.0"`

`librarian-puppet install` fails with:

/usr/lib/ruby/1.8/tsort.rb:152:in `tsort_each': topological sort failed: ["theforeman/apache", "theforeman/passenger"] (TSort::Cyclic)
    from /usr/lib/ruby/1.8/tsort.rb:183:in`each_strongly_connected_component'
    from /usr/lib/ruby/1.8/tsort.rb:210:in `each_strongly_connected_component_from'
...

It looks like "theforeman/apache" depends directly on "theforeman/passenger" and vice versa.  Not sure how to resolve this.  I guess in this instance it doesn't matter which one gets installed first as long as they both get installed.

**Comment by carlossg** [comment]
that's a tough one, I don't see how the dependency mechanism is going to work with cyclic dependencies, they need to fix it at the source. Cyclic dependencies are evil
